const JWT_CONST = {
  // GENERAL_SECRET: process.env.JWT_SECRET,
  // ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  // REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  TEACHER_JOIN_CLASS_EXPIRED: 84600, // 1 day
  ACCESS_TOKEN_EXPIRED: 7 * 24 * 60 * 60 * 1000, // 7d
  REFRESH_TOKEN_EXPIRED: 30 * 24 * 60 * 60 * 1000, //30d
};

export default JWT_CONST;
